name: Update Repository File and Create PR

on:
  push:
    branches:
      - test

jobs:
  update-file-and-create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - name: Update Repository File and Create PR
        id: update-file-and-create-pr
        uses: akfmdl/github-actions-workflows/actions/update-repo-and-create-pr@test
        with:
          target-repo: https://github.com/akfmdl/mlops-lifecycle.git
          file-path: Makefile
          variable-name: DUBBING_VERSION
          new-value: 1.0.0
          github-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update DUBBING_VERSION to 1.0.0
          pr-title: Update DUBBING_VERSION to 1.0.0
          pr-body: Update DUBBING_VERSION to 1.0.0

      - name: Post-pull-request notification
        if: steps.update-file-and-create-pr.outputs.pr_url != ''
        run: |
          echo "ğŸ‰ Pull Requestê°€ ìƒì„±ë˜ì—ˆìŠµë‹ˆë‹¤!"
          echo "Pull Request URL: ${{ steps.update-file-and-create-pr.outputs.pr-url }}"
          echo "Pull Request Number: ${{ steps.update-file-and-create-pr.outputs.pr-number }}"
          echo "Branch Name: ${{ steps.update-file-and-create-pr.outputs.branch-name }}"